name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ] 

env: 
  APP_NAME: python-flask-app
  IMAGE_NAME: python-flask-app
  NAMESPACE: github-copilot-ns

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Run Python tests
      run: |
        python -m pytest test_app.py -v --tb=short

    - name: Install Snyk CLI
      run: |
        curl -Lo snyk https://github.com/snyk/snyk/releases/latest/download/snyk-linux
        chmod +x snyk
        sudo mv snyk /usr/local/bin/

    - name: Authenticate with Snyk
      run: |
        if [ -z "${{ secrets.SNYK_TOKEN }}" ]; then
          echo "SNYK_TOKEN secret is not set - skipping Snyk authentication"
          echo "SNYK_AUTH_SUCCESS=false" >> $GITHUB_ENV
          exit 0
        fi
        echo "Authenticating with Snyk..."
        if snyk auth ${{ secrets.SNYK_TOKEN }}; then
          echo "Snyk authentication successful"
          echo "SNYK_AUTH_SUCCESS=true" >> $GITHUB_ENV
        else
          echo "Snyk authentication failed - continuing pipeline without Snyk"
          echo "SNYK_AUTH_SUCCESS=false" >> $GITHUB_ENV
        fi
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true

    - name: Snyk dependency vulnerability scan
      if: env.SNYK_AUTH_SUCCESS == 'true'
      run: |
        echo "Running Snyk dependency scan..."
        snyk test --severity-threshold=high --file=requirements.txt || echo "Snyk scan completed with issues (continuing due to continue-on-error)"
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:latest

    - name: Snyk container vulnerability scan
      if: env.SNYK_AUTH_SUCCESS == 'true'
      run: |
        echo "Running Snyk container scan..."
        snyk container test ${{ env.IMAGE_NAME }}:${{ github.sha }} --severity-threshold=high || echo "Snyk container scan completed with issues (continuing due to continue-on-error)"
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - name: Login to Azure Container Registry
      run: |
        echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    - name: Push Docker image to ACR
      run: |
        docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest

    - name: Generate Snyk security report
      if: env.SNYK_AUTH_SUCCESS == 'true'
      run: |
        echo "Generating Snyk security reports..."
        snyk monitor --file=requirements.txt || echo "Snyk dependency monitoring completed"
        snyk container monitor ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} || echo "Snyk container monitoring completed"
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true

    - name: Security scan summary
      run: |
        echo "=== Security Scan Summary ==="
        if [ "${{ env.SNYK_AUTH_SUCCESS }}" == "true" ]; then
          echo "✅ Snyk: Authentication successful, scans completed"
        else
          echo "❌ Snyk: Authentication failed, scans skipped"
          echo "💡 To fix: Update SNYK_TOKEN secret with valid token from https://snyk.io"
        fi
        echo "ℹ️  Pipeline continues regardless of Snyk status"
        echo "🔒 Security scanning is important but won't block deployment"

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: '1.28.0'

    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

    - name: Replace variables in deployment file
      run: |
        sed -i 's|${REGISTRY_LOGIN_SERVER}|${{ secrets.REGISTRY_LOGIN_SERVER }}|g' k8s-deployment.yaml
        sed -i 's|${IMAGE_NAME}|${{ env.IMAGE_NAME }}|g' k8s-deployment.yaml
        sed -i 's|${GITHUB_SHA}|${{ github.sha }}|g' k8s-deployment.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s-deployment.yaml

    - name: Verify deployment
      run: |
        kubectl rollout status deployment/${{ env.APP_NAME }} -n ${{ env.NAMESPACE }} --timeout=300s
        kubectl get pods -n ${{ env.NAMESPACE }} -l app=${{ env.APP_NAME }}
        kubectl get svc -n ${{ env.NAMESPACE }} ${{ env.APP_NAME }}-service

    - name: Health check
      run: |
        kubectl wait --for=condition=ready pod -l app=${{ env.APP_NAME }} -n ${{ env.NAMESPACE }} --timeout=300s
        echo "Application deployed successfully!"

    - name: Get application URL
      run: |
        echo "Application is running in namespace: ${{ env.NAMESPACE }}"
        echo "Service name: ${{ env.APP_NAME }}-service"
        echo "To access the application, use port forwarding:"
        echo "kubectl port-forward svc/${{ env.APP_NAME }}-service 8080:80 -n ${{ env.NAMESPACE }}"
